In [2]:
import numpy as np
import pandas as pd

In [2]:
#Question 1
np.__version__

'1.21.5'

In [3]:
#Question 2

In [32]:
df = pd.read_csv("d:\maschineLearning\zoomcamp\week1\data.csv")

In [5]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [6]:
df.shape[0]

11914

In [7]:
#Question 3
#the most frequent car manufacturers (top-3)

In [8]:
df[df['Make']=='BMW']

Make       Model  Year             Engine Fuel Type  Engine HP  \
0      BMW  1 Series M  2011  premium unleaded (required)      335.0   
1      BMW    1 Series  2011  premium unleaded (required)      300.0   
2      BMW    1 Series  2011  premium unleaded (required)      300.0   
3      BMW    1 Series  2011  premium unleaded (required)      230.0   
4      BMW    1 Series  2011  premium unleaded (required)      230.0   
...    ...         ...   ...                          ...        ...   
11901  BMW          Z4  2016  premium unleaded (required)      240.0   
11902  BMW          Z4  2016  premium unleaded (required)      335.0   
11903  BMW          Z8  2001  premium unleaded (required)      394.0   
11904  BMW          Z8  2002  premium unleaded (required)      394.0   
11905  BMW          Z8  2003  premium unleaded (required)      394.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL  rear wheel drive              2.0   
1                   6.0            MANUAL  rear wheel drive              2.0   
2                   6.0            MANUAL  rear wheel drive              2.0   
3                   6.0            MANUAL  rear wheel drive              2.0   
4                   6.0            MANUAL  rear wheel drive              2.0   
...                 ...               ...               ...              ...   
11901               4.0            MANUAL  rear wheel drive              2.0   
11902               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11903               8.0            MANUAL  rear wheel drive              2.0   
11904               8.0            MANUAL  rear wheel drive              2.0   
11905               8.0            MANUAL  rear wheel drive              2.0   

                             Market Category Vehicle Size Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                         Luxury,Performance      Compact   Convertible   
2                    Luxury,High-Performance      Compact         Coupe   
3                         Luxury,Performance      Compact         Coupe   
4                                     Luxury      Compact   Convertible   
...                                      ...          ...           ...   
11901                     Luxury,Performance      Compact   Convertible   
11902                Luxury,High-Performance      Compact   Convertible   
11903         Exotic,Luxury,High-Performance      Compact   Convertible   
11904         Exotic,Luxury,High-Performance      Compact   Convertible   
11905         Exotic,Luxury,High-Performance      Compact   Convertible   

       highway MPG  city mpg  Popularity    MSRP  
0               26        19        3916   46135  
1               28        19        3916   40650  
2               28        20        3916   36350  
3               28        18        3916   29450  
4               28        18        3916   34500  
...            ...       ...         ...     ...  
11901           34        22        3916   49700  
11902           24        17        3916   66350  
11903           19        12        3916  128000  
11904           19        12        3916  130000  
11905           19        12        3916  131500  

[334 rows x 16 columns]

In [9]:
df.groupby('Make').Make.count().sort_values(ascending = False)

Make
Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
McLaren             5
Alfa Romeo          5
Spyke

In [10]:
#Question 4

In [11]:
df[df["Make"]=="Audi"].nunique()

Make                   1
Model                 34
Year                  20
Engine Fuel Type       5
Engine HP             40
Engine Cylinders       6
Transmission Type      3
Driven_Wheels          2
Number of Doors        2
Market Category       15
Vehicle Size           3
Vehicle Style          6
highway MPG           23
city mpg              18
Popularity             1
MSRP                 234
dtype: int64

In [12]:
df[df["Make"]=="Audi"].Model.nunique()

34

In [13]:
df.groupby('Make').nunique()

Model  Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
Make                                                                        
Acura             18    22                 3         27                 3   
Alfa Romeo         1     2                 1          1                 1   
Aston Martin      12    11                 1         13                 2   
Audi              34    20                 5         40                 6   
BMW               39    18                 5         37                 5   
Bentley           18    12                 2         16                 2   
Bugatti            1     2                 1          1                 1   
Buick             20    19                 4         29                 3   
Cadillac          30    25                 5         32                 3   
Chevrolet         63    27                 7         68                 6   
Chrysler          19    23                 3         27                 3   
Dodge             33    27                 4         58                 4   
FIAT               5     3                 3          4                 2   
Ferrari           14    14                 1         16                 2   
Ford              51    28                 5         70                 5   
GMC               30    26                 3         30                 4   
Genesis            1     1                 2          2                 2   
HUMMER             2     3                 2          3                 2   
Honda             21    20                 5         31                 3   
Hyundai           22    19                 2         40                 3   
Infiniti          38    25                 3         33                 3   
Kia               16    10                 3         29                 4   
Lamborghini        6     9                 1         12                 2   
Land Rover        11    16                 5         11                 3   
Lexus             46    24                 3         41                 4   
Lincoln           16    21                 4         20                 3   
Lotus              5     9                 2          9                 3   
Maserati           8     8                 1         10                 2   
Maybach            3     3                 1          4                 1   
Mazda             31    26                 4         44                 2   
McLaren            4     4                 1          4                 1   
Mercedes-Benz     40    21                 5         56                 6   
Mitsubishi        22    25                 4         30                 4   
Nissan            32    20                 4         40                 4   
Oldsmobile        18    15                 2         18                 3   
Plymouth          10     9                 3         12                 2   
Pontiac           20    19                 4         39                 3   
Porsche           12    12                 3         29                 4   
Rolls-Royce       10     7                 1          5                 2   
Saab               8    11                 4         19                 3   
Scion              8     8                 2          9                 1   
Spyker             1     1                 1          1                 1   
Subaru            16    17                 3         21                 3   
Suzuki            16    21                 1         17                 2   
Tesla              1     3                 1          0                 1   
Toyota            39    22                 5         43                 4   
Volkswagen        31    23                 6         27                 6   
Volvo             26    24                 3         22                 3   

               Transmission Type  Driven_Wheels  Number of Doors  \
Make                                                               
Acura                       

In [14]:
#Question 5

In [31]:
df.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [16]:
np.count_nonzero(df.isna().sum().values) 

5

In [17]:
#Question 6

In [18]:
df['Engine Cylinders'].median()  #1

6.0

In [33]:
mode = df['Engine Cylinders'].mode()    #2
mode

0    4.0
Name: Engine Cylinders, dtype: float64

In [38]:
mode.values[0]

4.0

In [42]:
df['Engine Cylinders'].fillna(df['Engine Cylinders'].mode().values[0], inplace = True)

In [44]:
df['Engine Cylinders'].median()

6.0

In [43]:
#df2['Engine Cylinders'].fillna(mode, inplace = True)
df.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders        0
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [45]:
#Question 7

In [48]:
df_lotus = df[df['Make']=='Lotus'] #1
df_lotus

Make      Model  Year                Engine Fuel Type  Engine HP  \
3912  Lotus      Elise  2009     premium unleaded (required)      189.0   
3913  Lotus      Elise  2009     premium unleaded (required)      218.0   
3914  Lotus      Elise  2009     premium unleaded (required)      189.0   
3915  Lotus      Elise  2010     premium unleaded (required)      189.0   
3916  Lotus      Elise  2010     premium unleaded (required)      218.0   
3917  Lotus      Elise  2011     premium unleaded (required)      189.0   
3918  Lotus      Elise  2011     premium unleaded (required)      217.0   
3919  Lotus      Elise  2011     premium unleaded (required)      217.0   
4216  Lotus     Esprit  2002     premium unleaded (required)      350.0   
4217  Lotus     Esprit  2003     premium unleaded (required)      350.0   
4218  Lotus     Esprit  2004     premium unleaded (required)      350.0   
4257  Lotus  Evora 400  2017     premium unleaded (required)      400.0   
4258  Lotus  Evora 400  2017     premium unleaded (required)      400.0   
4259  Lotus      Evora  2011     premium unleaded (required)      276.0   
4260  Lotus      Evora  2011     premium unleaded (required)      276.0   
4261  Lotus      Evora  2013     premium unleaded (required)      276.0   
4262  Lotus      Evora  2013     premium unleaded (required)      345.0   
4263  Lotus      Evora  2013     premium unleaded (required)      345.0   
4264  Lotus      Evora  2013     premium unleaded (required)      276.0   
4265  Lotus      Evora  2014     premium unleaded (required)      345.0   
4266  Lotus      Evora  2014     premium unleaded (required)      276.0   
4267  Lotus      Evora  2014     premium unleaded (required)      345.0   
4268  Lotus      Evora  2014     premium unleaded (required)      276.0   
4292  Lotus      Exige  2009  premium unleaded (recommended)      257.0   
4293  Lotus      Exige  2009  premium unleaded (recommended)      240.0   
4294  Lotus      Exige  2010  premium unleaded (recommended)      240.0   
4295  Lotus      Exige  2011  premium unleaded (recommended)      240.0   
4296  Lotus      Exige  2011  premium unleaded (recommended)      257.0   
4297  Lotus      Exige  2011  premium unleaded (recommended)      257.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   
3917               4.0            MANUAL  rear wheel drive              2.0   
3918               4.0            MANUAL  rear wheel drive              2.0   
3919               4.0            MANUAL  rear wheel drive              2.0   
4216               8.0            MANUAL  rear wheel drive              2.0   
4217               8.0            MANUAL  rear wheel drive              2.0   
4218               8.0            MANUAL  rear wheel drive              2.0   
4257               6.0            MANUAL  rear wheel drive              2.0   
4258               6.0            MANUAL  rear wheel drive              2.0   
4259               6.0            MANUAL  rear wheel drive              2.0   
4260               6.0            MANUAL  rear wheel drive              2.0   
4261               6.0            MANUAL  rear wheel drive              2.0   
4262               6.0            MANUAL  rear wheel drive              2.0   
4263               6.0            MANUAL  rear wheel drive              2.0   
4264               6.0            MANUAL  rear wheel drive              2.0   
4265               6.0            MANUAL  rear wheel drive              2.0   
4266               6.0            MANUAL  rear wheel drive              2.0   
4267              

In [51]:
df_lotus_two_col = df_lotus[["Engine HP", "Engine Cylinders"]] #2
df_lotus_two_col

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [59]:
df_lotus_two_col_unique = df_lotus_two_col.drop_duplicates() #3
df_lotus_two_col_unique

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [112]:
X = np.zeros([9,2])
X

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [114]:
X[:,0] = df_lotus_two_col_unique["Engine HP"].values
X[:,1] = df_lotus_two_col_unique["Engine Cylinders"].values

In [115]:
X #4

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [116]:
X.T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [117]:
X.T.shape

(2, 9)

In [118]:
XTX =(X.T).dot(X) #5
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [119]:
inv = np.linalg.inv(XTX) #6
inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [120]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]) #7
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [121]:
mat = inv.dot(X.T)
mat

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [122]:
mat.dot(y)

array([  4.59494481, -63.56432501])

In [ ]:
``